### ISSUE TITLE
Add "Save as..." command to save to new config file

### ISSUE THREAD

**Issue by semagnum** [semagnum/blint#36]
I often will save the internal/default config to a new file so I can make custom rules specific to the new config. Instead of having to:

1. Create/point to new JSON file
2. Copy-and-paste from internal config to another
3. Point to External new config file

Add a new "Save as..." option where it saves the currently used config to a new file, and re-points the external config path to the new config.

**Comment by kbruh** [comment]
Hello, can you assign me?

**Comment by kbruh** [comment]
You mean to create a function in Python that can "save as" JSON files or something like that? If that's the case, then I have finished. How can I share this code with you? Btw, I'm a newbie

**Comment by semagnum** [comment]
Hi @kbruh ! Thanks so much for commenting and wanting to contribute. I took a look at the pull request, and sadly I don't think it would work as is. I should clarify further what this will require (hopefully exhaustive, but may need some tinkering):

- adding a new `bpy.types.Operator` that:
  - prompts the user to save to a new file
  - retrieves the currently used rules (internal or external), and saves them to a new file
  - switch the preference's rule type to external
  - set the preference's external filepath to the new path the user just saved to.
- register (and unregister) said operator
- Add this operator to my `BT_MT_config_menu`'s `draw()` function, with the text something like "Save current rules as..."

Hope that makes sense. The functionality you coded would go in that operator, but you'd need to use BLint's existing variables and functions.

If you still feel up to the task, I can assign you.
